image: Ubuntu2204
stack: node 20
branches:
  only:
    - master
    - main
cache: node_modules
install:
  - npm install
build: off
build_script:
  - npm run build
test_script:
  - npm run lint && npm run test
